### ISSUE TITLE
Jenkins build

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/Bergeypvp#1]

**Comment by WildWeazel** [comment]
needs a pom, remove the bin files, and maybe depends on bergemodcore?

**Comment by WildWeazel** [comment]
@valadian pls advise

**Comment by WildWeazel** [comment]
@ttk2 I shared the Bergecraft jars folder with you on GDrive. Please copy **bergmodcore.jar** (Humbug-style annotations for console config) and **gimmickapi.jar** (no-op API declaration to compile against) onto the Jenkins server at **/var/lib/jenkins/workspace/lib-setup/**

**Comment by ttk2** [comment]
do we have source for those two? Do we want to link them up for their own
builds on jenkins like we do with our other dependencies that we control.

**Comment by WildWeazel** [comment]
We can, the sources are from Bergecraft and TJ respectively, but that's two more repos to fork and writes poms for, that I don't expect will ever change. If we're going to be doing much work on this code I'd suggest stripping out both of those dependencies and using Namelayer's annotation system instead.

**Comment by Valadian** [comment]
Gimmickapi is easy to extract. But that limits testing opportunity on civpvp
On Apr 5, 2015 2:59 PM, Travis Christian notifications@github.com wrote:We can, the sources are from Bergecraft and TJ respectively, but that's two more repos to fork and writes poms for, that I don't expect will ever change. If we're going to be doing much work on this code I'd suggest stripping out both of those dependencies and using Namelayer's annotation system instead.

**Comment by ttk2** [comment]
Ok then, I can put them up, would it be easier for long term changes if we
did somthing besides this? Or is keeping these dependencies around not
going to weigh us down?

**Comment by WildWeazel** [comment]
I don't see any reason we'd ever need to update/rebuild them, so treating them as third party libraries seems fine

**Comment by ttk2** [comment]
Very well then. Where would I compare these jars to if I wanted to check
them or build them myself?

**Comment by Valadian** [comment]
Bergecraft/BergModCore
|   |
|   |  |   |   |   |   |   |
| Bergecraft/BergModCoreBergModCore - Common Plugin Core derived from Humbug |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

Bergecraft/GimmickAPI
|   |
|   |  |   |   |   |   |   |
| Bergecraft/GimmickAPIGimmickAPI - API for interacting with the Gimmicks minecraft plugin. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

```
 On Monday, April 6, 2015 7:48 AM, ttk2 <notifications@github.com> wrote:
```

 Very well then. Where would I compare these jars to if I wanted to check
them or build them myself?

**Comment by ttk2** [comment]
it has been done.

**Comment by WildWeazel** [comment]
permission denied, the Jenkins user needs read on them

**Comment by ttk2** [comment]
whoops fixed.

**Comment by WildWeazel** [comment]
http://civcraft.co:8080/job/BergeyPvP-master/3/

**Comment by ttk2** [comment]
yay, time for Civtest.

**Comment by ttk2** [comment]
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError:
com/valadian/bergecraft/ABergMod
        at
org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NoClassDefFoundError: com/valadian/bergecraft/ABergMod
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
~[?:1.7.0_75]
        at
java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
~[?:1.7.0_75]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
~[?:1.7.0_75]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method)
~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
~[?:1.7.0_75]
        at
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
~[?:1.7.0_75]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
        at
org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 6 more

**Comment by WildWeazel** [comment]
Oh, yeah. You have to load both. (Or I figure out how to repackage libraries with Maven since this is the only plugin that ever used it) Does that change the dependency question?

**Comment by rourke750** [comment]
Look at mercury for the maven stuff
